import type { DiagnosticItem } from "./types.ts";

export const DIAGNOSTICS: DiagnosticItem[] = [
  {
    id: "dq-agent-memory-persistence",
    conceptId: "agent-memory",
    type: "multiple_choice",
    prompt:
      "An agent finishes a coding session on Monday. On Tuesday a new session starts with an empty context window. With persistent memory enabled, what is most likely available to the agent at the start of Tuesday's session?",
    choices: [
      "Monday's full transcript, placed verbatim into Tuesday's context window",
      "Distilled facts and preferences written to a memory store, retrieved when relevant to the new task",
      "Nothing: a model cannot retain anything between sessions without retraining",
      "Updated model weights, fine-tuned overnight on Monday's session",
    ],
    choiceCorrectness: [0.35, 1, 0, 0],
    choiceFeedback: [
      "Close, but memory is not the old transcript replayed. That would just be a bigger context window, and it would not scale across weeks of sessions.",
      "Right. What persists is a curated store of distilled facts, and the agent retrieves only what is relevant. The context window is still empty at the start. Memory lives outside it.",
      "Memory doesn't require retraining. The model stays the same; what changes is an external store the agent reads from and writes to.",
      "Persistent memory doesn't touch the weights. It's an external store the agent queries, which is why it can be inspected and corrected.",
    ],
    choiceMisconception: ["memory-equals-context-window", null, "memory-requires-retraining", "memory-requires-retraining"],
    expectedConcepts: ["agent-memory", "context-windows", "memory-consolidation"],
    rationale: "A transfer question: it asks what state survives a session boundary, which separates persistent memory from a long context window.",
    evidencePhrase: "a transfer question about what state persists across sessions",
    targetsMisconception: "memory-equals-context-window",
  },
  {
    id: "dq-agent-memory-short",
    conceptId: "agent-memory",
    type: "short_answer",
    prompt: "In one or two sentences: why is persistent agent memory not the same thing as a very large context window?",
    expectedConcepts: ["agent-memory", "context-windows"],
    rationale: "Asks the learner to articulate the distinction in their own words.",
    evidencePhrase: "a question asking you to explain memory vs. context in your own words",
    rubric: [
      { idea: "Memory persists across sessions; context is per request/session", keywords: ["session", "persist", "across", "later", "between"] },
      { idea: "Memory is selectively retrieved/curated rather than everything being present", keywords: ["retriev", "select", "relevant", "store", "curat", "distill"] },
    ],
    targetsMisconception: "memory-equals-context-window",
  },
  {
    id: "dq-memory-consolidation",
    conceptId: "memory-consolidation",
    type: "multiple_choice",
    prompt: "Why do newer agent memory systems consolidate memories at write time instead of storing raw transcripts?",
    choices: [
      "Raw transcripts are illegal to store",
      "Distilled, deduplicated facts are cheaper to search and less likely to surface stale or contradictory details",
      "Consolidation makes the model's context window larger",
      "It removes the need for any retrieval step",
    ],
    choiceCorrectness: [0, 1, 0, 0.2],
    choiceFeedback: [
      "This is an engineering choice, not a legal one.",
      "Right. Consolidation keeps the store compact and consistent, so recall stays relevant.",
      "Consolidation doesn't change the context window. It changes what gets stored outside it.",
      "Retrieval still happens. Consolidation just makes what's retrieved cleaner.",
    ],
    choiceMisconception: [null, null, "memory-equals-context-window", null],
    expectedConcepts: ["memory-consolidation", "agent-memory"],
    rationale: "Checks whether the learner understands the write-time vs read-time tradeoff.",
  },
  {
    id: "dq-long-horizon",
    conceptId: "long-horizon-agents",
    type: "multiple_choice",
    prompt: "What most limits an agent that must work on the same project across many days?",
    choices: [
      "Its typing speed",
      "Carrying forward what it learned and verifying that it is still correct",
      "The number of tools it can call per minute",
      "The font size of its output",
    ],
    choiceCorrectness: [0, 1, 0.2, 0],
    choiceFeedback: [
      "Speed isn't the bottleneck over days.",
      "Right. Continuity (memory) and correctness (evaluation) are the long-horizon bottlenecks.",
      "Rate limits matter, but continuity and verification matter more over days.",
      "Not relevant here.",
    ],
    expectedConcepts: ["long-horizon-agents", "agent-memory", "evaluator-architectures"],
    rationale: "Connects long-horizon work to memory and evaluation.",
  },
  {
    id: "dq-evaluator",
    conceptId: "evaluator-architectures",
    type: "multiple_choice",
    prompt: "Why might a separate evaluator model catch errors that an agent's own self-critique misses?",
    choices: [
      "It is always a larger model",
      "It judges against its own explicit criteria and does not share the agent's reasoning path or blind spots",
      "It can see the future",
      "It runs the agent's unit tests, and that is all an evaluator does",
    ],
    choiceCorrectness: [0.1, 1, 0, 0.3],
    choiceFeedback: [
      "Size helps sometimes, but independence is the key property.",
      "Right. An independent evaluator doesn't inherit the agent's framing, so it catches errors that self-review rationalizes away.",
      "No.",
      "Tests are one kind of evaluation. Evaluator architectures also grade open-ended output against criteria.",
    ],
    choiceMisconception: [null, null, null, "evaluator-equals-unit-test"],
    expectedConcepts: ["evaluator-architectures"],
    rationale: "Probes the independence principle behind evaluator architectures.",
  },
  {
    id: "dq-mcp",
    conceptId: "mcp",
    type: "multiple_choice",
    prompt: "What problem does the Model Context Protocol primarily solve?",
    choices: [
      "Training models faster",
      "Giving every application a standard way to expose tools and context to any compatible model client",
      "Compressing context windows",
      "Replacing tool use entirely",
    ],
    choiceCorrectness: [0, 1, 0, 0],
    choiceFeedback: [
      "MCP is about integration, not training.",
      "Right. It standardizes the integration layer, so tools are written once and work with many clients.",
      "That's compaction, a different concept.",
      "MCP is built on tool use; it doesn't replace it.",
    ],
    expectedConcepts: ["mcp", "agent-tool-use"],
    rationale: "Checks the core purpose of MCP.",
  },
  {
    id: "dq-context-windows",
    conceptId: "context-windows",
    type: "multiple_choice",
    prompt: "A fact was mentioned 400k tokens ago in a conversation with a 200k-token window and no compaction. What does the model see?",
    choices: ["The fact, slightly blurred", "Nothing: it is outside the window", "A summary of it", "Only its first sentence"],
    choiceCorrectness: [0, 1, 0.2, 0],
    choiceFeedback: [
      "No. Tokens outside the window aren't visible at all.",
      "Right. Anything outside the window is invisible to that request.",
      "Only if compaction or memory produced a summary, which it didn't here.",
      "No partial visibility.",
    ],
    expectedConcepts: ["context-windows"],
    rationale: "Baseline check of the context boundary.",
  },
  {
    id: "dq-rag",
    conceptId: "retrieval-augmented-generation",
    type: "multiple_choice",
    prompt: "What does a classic RAG system retain after answering a question?",
    choices: ["Nothing about the interaction", "A fine-tuned copy of the model", "A memory of the user's preferences", "The whole conversation in its weights"],
    choiceCorrectness: [1, 0, 0.2, 0],
    choiceFeedback: [
      "Right. Classic RAG is stateless: it retrieves, answers and forgets.",
      "No training happens in RAG.",
      "That would be agent memory, not classic RAG.",
      "No weights change.",
    ],
    expectedConcepts: ["retrieval-augmented-generation"],
    rationale: "Separates RAG (stateless retrieval) from memory.",
  },
  {
    id: "dq-agent-tool-use",
    conceptId: "agent-tool-use",
    type: "multiple_choice",
    prompt: "An agent's tool call returns an error. What should a well-designed agent loop do next?",
    choices: [
      "Crash",
      "Feed the error back to the model as a tool result so it can adjust its next call",
      "Silently retry the identical call forever",
      "Hide the error from the model",
    ],
    choiceCorrectness: [0, 1, 0.2, 0],
    choiceFeedback: ["No.", "Right. Errors are information the model can use.", "Blind retries waste budget.", "Hiding errors prevents recovery."],
    expectedConcepts: ["agent-tool-use"],
    rationale: "Checks error-handling in the tool loop.",
  },
  {
    id: "dq-context-compaction",
    conceptId: "context-compaction",
    type: "multiple_choice",
    prompt: "What is the main tradeoff of compacting a long conversation?",
    choices: [
      "It costs nothing and loses nothing",
      "It keeps the session within the window but can drop details that later turn out to matter",
      "It permanently stores memories across sessions",
      "It makes the model smarter",
    ],
    choiceCorrectness: [0, 1, 0, 0],
    choiceFeedback: [
      "Summaries always lose some detail.",
      "Right. Compaction trades detail for continuity within a session.",
      "Compaction is within-session; cross-session persistence is memory.",
      "No.",
    ],
    choiceMisconception: [null, null, "memory-equals-context-window", null],
    expectedConcepts: ["context-compaction", "context-windows"],
    rationale: "Distinguishes compaction from memory.",
  },
];
