/**
 * Seeded prior history for the demo persona. It is generated by replaying
 * observations through the real update rule, so the baseline state and its
 * history are always consistent with the engine.
 */
import type { Concept, KnowledgeState, KnowledgeStateTransition, ObservationKind } from "@thinketh/contracts";
import { applyObservation, explainUpdate, type UpdateOptions } from "../engine/knowledgeState.ts";
import { makeObservation } from "../engine/observations.ts";
import { DAY_MS, newId } from "../util.ts";

export type HistoryStep = { daysAgo: number; kind: ObservationKind; correctness?: number; options?: UpdateOptions };

export function replayHistory(
  start: KnowledgeState,
  steps: HistoryStep[],
  concept: Concept,
  now: Date,
): { transitions: KnowledgeStateTransition[]; end: KnowledgeState } {
  let state = start;
  const transitions: KnowledgeStateTransition[] = [];
  for (const step of steps) {
    const at = new Date(now.getTime() - step.daysAgo * DAY_MS);
    const observation = makeObservation({
      userId: start.userId,
      conceptId: start.conceptId,
      kind: step.kind,
      ...(step.correctness !== undefined ? { correctness: step.correctness } : {}),
      sourceRef: "seed:history",
      now: at,
    });
    const options = step.options ?? {};
    const update = applyObservation(state, observation, at, options);
    transitions.push({
      id: newId("kst"),
      userId: start.userId,
      conceptId: start.conceptId,
      before: state,
      observation,
      after: update.after,
      reason: explainUpdate({ concept, before: state, after: update.after, observation, staleness: update.staleness, options }),
      propagatedChanges: [],
      createdAt: observation.createdAt,
    });
    state = update.after;
  }
  return { transitions, end: state };
}
